version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: TheBeautyHubAPI/Dockerfile
    container_name: tbh-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
    restart: unless-stopped
    network_mode: host
